/**
 * PRODUCT VIDEO TYPES — Data structures for 6-scene template
 * All scene data is generated by the Prompt Engine and passed
 * as props to each Remotion composition.
 */

import { z } from "zod";

// === Constants ===

export const FPS = 30;
export const VIDEO_WIDTH = 1080;
export const VIDEO_HEIGHT = 1920;

// Safe zones for TikTok/Reels
export const SAFE_ZONE = {
  top: 150,
  bottom: 170,
  left: 60,
  right: 60,
} as const;

export const CONTENT_WIDTH = VIDEO_WIDTH - SAFE_ZONE.left - SAFE_ZONE.right; // 960px

// Scene durations in seconds
export const SCENE_DURATIONS = {
  hook: 3,
  productIntro: 3,
  simulatedDemo: 8,
  imageShowcase: 5,
  featureCallouts: 3,
  socialProofCta: 3,
} as const;

export const TOTAL_DURATION_SECONDS = Object.values(SCENE_DURATIONS).reduce(
  (a, b) => a + b,
  0
); // 25s

export const TOTAL_FRAMES = TOTAL_DURATION_SECONDS * FPS; // 750

// === Scene Data Schemas ===

export const BrandColorsSchema = z.object({
  primary: z.string().describe("Primary brand color hex"),
  secondary: z.string().describe("Secondary brand color hex"),
  accent: z.string().describe("Accent/highlight color hex"),
  background: z.string().default("#0a0a0a").describe("Dark background hex"),
  text: z.string().default("#ffffff").describe("Primary text color hex"),
});

export const HookSceneSchema = z.object({
  painPointQuestion: z
    .string()
    .describe('Bold pain-point question, e.g. "Still editing videos manually?"'),
});

export const ProductIntroSceneSchema = z.object({
  productName: z.string(),
  tagline: z.string().describe("Real tagline or hero headline from the product"),
  logoPath: z.string().optional().describe("Path to downloaded logo image"),
});

export const DemoStepSchema = z.object({
  action: z
    .enum(["click_input", "type_text", "click_button", "show_result"])
    .describe("What the animated cursor does"),
  label: z.string().describe("Text for the UI element (input placeholder, button text, result text)"),
  durationFrames: z.number().describe("How many frames this step takes"),
});

export const SimulatedDemoSceneSchema = z.object({
  inputPlaceholder: z.string().describe('Placeholder text for the input field, e.g. "Enter your prompt..."'),
  typedText: z.string().describe("Text that types into the input field character by character"),
  buttonText: z.string().describe('CTA button text, e.g. "Generate"'),
  resultText: z.string().describe("Result that appears after button click"),
  resultSubtext: z.string().optional().describe("Optional secondary result text"),
});

export const ImageShowcaseSceneSchema = z.object({
  images: z
    .array(
      z.object({
        path: z.string().describe("Path to processed product image"),
        headline: z.string().describe("Short feature headline shown with this image, max 6 words"),
      })
    )
    .min(1)
    .max(4),
});

export const FeatureCalloutSchema = z.object({
  icon: z.enum(["check", "lightning", "star", "shield", "zap", "heart"]),
  text: z.string().describe("Short feature benefit text"),
});

export const FeatureCalloutsSceneSchema = z.object({
  features: z.array(FeatureCalloutSchema).min(2).max(4),
  productImagePath: z.string().describe("Product image to show scaled down at top"),
  featureTitle: z.string().optional().describe("Scene 4 header label — topic-specific (e.g. 'The DMAIC Steps')"),
});

export const SocialProofCtaSceneSchema = z.object({
  socialProofNumber: z.number().optional().describe("Number to count up to, e.g. 50000"),
  socialProofLabel: z.string().optional().describe('Label after the number, e.g. "happy users"'),
  ctaUrl: z.string().describe("Product URL or 'Link in bio'"),
});

// === Backgrounds (Pexels) ===

export const BackgroundsSchema = z.object({
  photos: z.array(z.string()).default([]).describe("Paths to background photos from Pexels"),
  videos: z.array(z.string()).default([]).describe("Paths to background videos from Pexels"),
}).optional();

// === Main Product Video Data ===

export const ProductVideoDataSchema = z.object({
  productSlug: z.string(),
  brandColors: BrandColorsSchema,
  hook: HookSceneSchema,
  productIntro: ProductIntroSceneSchema,
  simulatedDemo: SimulatedDemoSceneSchema,
  imageShowcase: ImageShowcaseSceneSchema,
  featureCallouts: FeatureCalloutsSceneSchema,
  socialProofCta: SocialProofCtaSceneSchema,
  narrationAudioPath: z.string().optional().describe("Path to full narration audio file"),
  backgrounds: BackgroundsSchema.describe("Pexels stock backgrounds for scene ambiance"),
});

// === Inferred Types ===

export type BrandColors = z.infer<typeof BrandColorsSchema>;
export type HookScene = z.infer<typeof HookSceneSchema>;
export type ProductIntroScene = z.infer<typeof ProductIntroSceneSchema>;
export type SimulatedDemoScene = z.infer<typeof SimulatedDemoSceneSchema>;
export type ImageShowcaseScene = z.infer<typeof ImageShowcaseSceneSchema>;
export type FeatureCallout = z.infer<typeof FeatureCalloutSchema>;
export type FeatureCalloutsScene = z.infer<typeof FeatureCalloutsSceneSchema>;
export type SocialProofCtaScene = z.infer<typeof SocialProofCtaSceneSchema>;
export type Backgrounds = z.infer<typeof BackgroundsSchema>;
export type ProductVideoData = z.infer<typeof ProductVideoDataSchema>;
